[package]
name = "rs100"
version = "0.1.0"
authors = ["Tatsuki Saito <cc_called_pizza@yahoo.co.jp>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
regex = "1"
rand = "0.7"
finalfusion = "0.12"
flate2 = "1.0"
